- name: Deploy Orders API
  hosts: API
  become: yes

  tasks:
    - name: Actualizar paquetes
      apt:
       update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Instalar dependencias
      package:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git 
        state: present
    - name: Crear carpeta de aplicacion
      file:
        path: /opt/api
        state: directory
        model: '0755'
        owner: {{ansible_user}}
    # - name: Copiar aplicacion
    # - name: Copiar requerimientos
    # - name: Copiar dependencias de aplicacion
    # - name: Crear el entorno virtual
    # - name: Iniciar la aplicacion